services:
  ttdl_postgres:
    container_name: ttdl_database
    image: postgres:16.2
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: "TTDL_Ortho"
      POSTGRES_USER: "TTDL_Ortho"
      POSTGRES_PASSWORD: "TTDL_pw"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ttdl_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ad.min
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '20080:80'
    volumes:
      - pgAdminData:/var/lib/pgadmin
    depends_on:
      ttdl_postgres:
        condition: service_healthy
    networks:
      - ttdl_network

  ttdl_backend:
    container_name: ttdl_backend
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "28080:8080"
    depends_on:
      ttdl_postgres:
        condition: service_healthy
    networks:
      - ttdl_network
    command: ["./wait-for-it.sh", "ttdl_postgres:5432", "--", "dotnet", "TTDL-Backend.dll"]

volumes:
  pgdata:
  pgAdminData:

networks:
  ttdl_network:
